//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PointOfInterest')
export class PointOfInterestEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('real', { nullable: true })
  longitude: number;

  @Column('real', { nullable: true })
  latitude: number;

  @Column('text', { nullable: true })
  media: string;
}
