//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    PointOfInterest: [
      {
        name: 'name 1',
        longitude: 0.01,
        latitude: 0.96,
        media: 'media 1',
        id: 93,
      },
      {
        name: 'name 2',
        longitude: 0.83,
        latitude: 0.48,
        media: 'media 2',
        id: 26,
      },
      {
        name: 'name 3',
        longitude: 0.64,
        latitude: 0.39,
        media: 'media 3',
        id: 23,
      },
      {
        name: 'name 4',
        longitude: 0.03,
        latitude: 0.89,
        media: 'media 4',
        id: 12,
      },
      {
        name: 'name 5',
        longitude: 0.47,
        latitude: 0,
        media: 'media 5',
        id: 32,
      },
    ],
  },
};
export default data;
