//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    PointOfInterest: {
      name: 'Point Of Interest',
      fields: {
        name: 'Name',
        longitude: 'Longitude',
        latitude: 'Latitude',
        media: 'Media',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    PointOfInterest: {
      name: 'Point Of Interest (fr)',
      fields: {
        name: 'Name (fr)',
        longitude: 'Longitude (fr)',
        latitude: 'Latitude (fr)',
        media: 'Media (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
